version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password

  order-service:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - ./services/order-service:/app
    environment:
      - DB_HOST=db      
    restart: always
    ports:
      - "80:80"

  frontend:
    image: nginx:latest
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"