events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # Frontend
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Auth Service
        location /api/auth/ {
            rewrite ^/api/auth/(.*) /$1 break;
            proxy_pass http://auth-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # User Service
        location /api/users/ {
            rewrite ^/api/users/(.*) /$1 break;
            proxy_pass http://user-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Product Service
        location /api/products/ {
            rewrite ^/api/products/(.*) /$1 break;
            proxy_pass http://product-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Chat Service
        location /api/chat/ {
            rewrite ^/api/chat/(.*) /$1 break;
            proxy_pass http://chat-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Order Service
        location /api/orders/ {
            rewrite ^/api/orders/(.*) /$1 break;
            proxy_pass http://order-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
