events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream order_backend {
        server order-service:80;
        server order-service-2:80; # Scaled instance
    }

    server {
        listen 80;

        # Frontend
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Auth Service
        location /api/auth/ {
            rewrite ^/api/auth/(.*) /$1 break;
            proxy_pass http://auth-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # User Profile Service
        location /api/users/ {
            rewrite ^/api/users/(.*) /$1 break;
            proxy_pass http://user-profile-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Product Service
        location /api/products/ {
            rewrite ^/api/products/(.*) /$1 break;
            proxy_pass http://product-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Payment Service
        location /api/payment/ {
            rewrite ^/api/payment/(.*) /$1 break;
            proxy_pass http://payment-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Notification Service
        location /api/notification/ {
            rewrite ^/api/notification/(.*) /$1 break;
            proxy_pass http://notification-service:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Order Service (Load Balanced)
        location /api/orders/ {
            rewrite ^/api/orders/(.*) /$1 break;
            proxy_pass http://order_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
